# C:/StylistAI/docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: stylist_ai_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=stylistai
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_DB=stylistai_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
    name: stylist_ai_postgres_data