services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stylist_ai_api
    command: >
      sh -c "poetry run alembic upgrade head &&
             poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app

  db:
    image: postgres:15-alpine
    container_name: stylist_ai_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - stylist_ai_postgres_data:/var/lib/postgresql/data

volumes:
  stylist_ai_postgres_data: